version: '3.7'

services:
  profile1:
    container_name: profile-dev
    image: profile
    build: .
    command: mvn spring-boot:run -Dagentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:4000
    volumes:
      - .:/profile
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    ports:
      - "4000:4000"
  profile2:
    container_name: profile-test
    image: profile
    command: mvn spring-boot:run -Dagentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:4100
    volumes:
      - .:/profile
    environment:
      - "SPRING_PROFILES_ACTIVE=test"
    ports:
      - "4100:4100"

